title: Rakugo Framework
email:
description: Rakugo Framework for Godot Engine
github_username: rakugoteam
minimal_mistakes_skin: dark
search: true

##Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
##Outputting
permalink: /:categories/:title/
paginate: 5 ##amount of posts to show
paginate_path: /page:num/
timezone: ##https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  avatar : "/assets/imgs_main/logo.png"
  links:
    - label: "itch.io"
      icon: "fas fa-fw fa-link"
      url: "https://jebedaia.itch.io/rakugo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rakugoteam/Rakugo"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rakugoteam/Rakugo"

defaults:
  ##_pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  ##_posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
