# Site settings
## Change the values as needed.
title: socd06
email: socd06@gmail.com
description: "Projects Portfolio"
keywords: "mechatronics, image processing, engineering"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://socd06.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 10
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: rouge #pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  email: socd06@gmail.com
  github: socd06
  linkedin: socd06-eng
exclude:
  - bower_components
  - README.md
full_name: Carlos Salgado

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
