title: Rakugo
email:
description: Rakugo for Godot Engine
github_username: rakugoteam
minimal_mistakes_skin: dark
search: true

##Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

##Outputting
permalink: /:categories/:title/
paginate: 5 ##amount of posts to show
paginate_path: /page:num/
timezone: ##https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts
  - _kits_addons

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# to make it work on GitHub:
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  avatar : "/assets/imgs_main/logo.png"
  links:
    - label: "Patreon"
      icon: "fab fa-fw fa-link"
      url: "https://www.patreon.com/rakguoteam"
    - label: "itch.io"
      icon: "fas fa-fw fa-shopping-bag"
      url: "https://jeremi360x.itch.io/rakugo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rakugoteam/Rakugo"
    - label: Discord
      icon: "fab fa-fw fa-link"
      url: "https://discord.gg/K9gvjdg"
    - label: "Youtube Channel"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/channel/UCuItFHsERbsyi8gLJ7Ti1KA"
    - label: "Docs"
      icon: "fab fa-fw fa-link"
      url: "https://rakugoteam.github.io/RakugoDocs/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rakugoteam/Rakugo"

defaults:
  ##_pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  ##_posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  ##_kits_addons
  - scope:
      path: "_kits_addons"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
      share: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
